#!/bin/bash
set -euo pipefail

# Generate an SRPM for a MINGW package by reading its PKGBUILD,
# downloading sources, and writing an RPM .spec file.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="${SCRIPT_DIR}/.."
source "${SCRIPT_DIR}/lib-mingw-pkg.sh"

if [[ $# -lt 1 ]]; then
    echo "Usage: $(basename "$0") <pkg> [output-dir]"
    echo ""
    echo "  pkg:        package name (e.g., libiconv, mingw-w64-libiconv)"
    echo "  output-dir: where to write spec + sources (default: rpmbuild-mingw/<pkg>/)"
    exit 1
fi

RAW_PKG="$1"
PKG=$(normalize_pkg "$RAW_PKG")

checkout_pkg "$PKG"
SRCDIR="${_checkout_actual}"
PKGBUILD="${MINGW_PACKAGES_DIR}/${SRCDIR}/PKGBUILD"

if [[ ! -f "$PKGBUILD" ]]; then
    err "PKGBUILD not found: ${PKGBUILD}"
    exit 1
fi

msg "Parsing PKGBUILD for ${SRCDIR}..."
eval "$(parse_pkgbuild "$PKGBUILD")"

OUTDIR="${2:-${REPO_DIR}/rpmbuild-mingw/${SRCDIR}}"
mkdir -p "${OUTDIR}"
OUTDIR="$(cd "${OUTDIR}" && pwd)"

msg "Package: ${SRCDIR} ${_pkgver}-${_pkgrel}"

download_sources "${SRCDIR}"

declare -A _dummies
load_dummy_packages _dummies

# Gettext sub-packages aren't available until gettext is built, but libiconv
# (which is built first) Requires them at runtime.  Filter only the gettext
# packages from BuildRequires so libiconv's RPM can be installed in mock
# without pulling in not-yet-built gettext.  Do NOT filter libiconv — packages
# like gettext legitimately need it at build time and it's already in the repo.
declare -A _base_provides=(
    [mingw-w64-ucrt-x86_64-gettext-runtime]=1
    [mingw-w64-ucrt-x86_64-gettext-libtextstyle]=1
    [mingw-w64-ucrt-x86_64-gettext-tools]=1
    [mingw-w64-ucrt-x86_64-gettext]=1
)

# Map MINGW dependencies to RPM tags
map_deps() {
    local -n _deps_in=$1
    local dep_type=$2
    local skip_base=${3:-0}
    for dep in "${_deps_in[@]}"; do
        [[ -z "$dep" ]] && continue
        dep="${dep%%[><=]*}"
        [[ "$dep" != mingw-w64-ucrt-x86_64-* ]] && continue
        [[ -n "${_dummies[$dep]+x}" ]] && continue
        [[ "$skip_base" -eq 1 && -n "${_base_provides[$dep]+x}" ]] && continue
        echo "${dep_type}: ${dep}"
    done
}

BUILD_DEPS=$(map_deps _makedepends "BuildRequires" 1)
BUILD_DEPS+=$'\n'$(map_deps _depends "BuildRequires" 1)
RUN_DEPS=$(map_deps _depends "Requires")

# Detect git sources — makepkg needs git to extract them
_has_git_source=0
for src in "${_source[@]}"; do
    [[ "$src" == *git+* ]] && _has_git_source=1
done

# Classify sources as URLs or local files
_source_urls=()
_source_locals=()
for src in "${_source[@]}"; do
    [[ -z "$src" ]] && continue
    url="${src##*::}"
    if [[ "$url" == http://* || "$url" == https://* || "$url" == ftp://* ]]; then
        _source_urls+=("$url")
    else
        fname="${src%%::*}"
        [[ "$fname" == "$src" ]] && fname="${url##*/}"
        _source_locals+=("$fname")
    fi
done

# Source0: PKGBUILD + local patches tarball
PKGBUILD_TAR="${SRCDIR}-pkgbuild.tar.gz"
msg "Creating ${PKGBUILD_TAR}..."
tar czf "${OUTDIR}/${PKGBUILD_TAR}" \
    -C "${MINGW_PACKAGES_DIR}" \
    "${SRCDIR}/"

# Symlink downloaded source tarballs into output dir
for url in "${_source_urls[@]}"; do
    fname="${url##*/}"
    src_file="${MINGW_PACKAGES_DIR}/${SRCDIR}/${fname}"
    if [[ -f "$src_file" ]]; then
        ln -sfn "$src_file" "${OUTDIR}/${fname}"
    else
        warn "Source not found: ${fname}"
    fi
done

# Check for msys2-cross cross-compilation patch
CROSS_PATCH="${REPO_DIR}/patches/${SRCDIR}.sh"
HAS_CROSS_PATCH=0
CROSS_PATCH_SRC_IDX=""
if [[ -f "$CROSS_PATCH" ]]; then
    HAS_CROSS_PATCH=1
    cp "$CROSS_PATCH" "${OUTDIR}/"
fi

# Build Source list for the spec
_spec_sources=()
_spec_sources+=("Source0: ${PKGBUILD_TAR}")
_src_idx=1
for url in "${_source_urls[@]}"; do
    _spec_sources+=("Source${_src_idx}: ${url}")
    (( _src_idx++ ))
done
if [[ "$HAS_CROSS_PATCH" -eq 1 ]]; then
    CROSS_PATCH_SRC_IDX="${_src_idx}"
    _spec_sources+=("Source${_src_idx}: ${SRCDIR}.sh")
fi

# Build %prep source copies
_prep_copies=""
_src_idx=1
for url in "${_source_urls[@]}"; do
    _prep_copies+="cp %{SOURCE${_src_idx}} %{pkgbase}/
"
    (( _src_idx++ ))
done

# License
_license_str=""
for l in "${_license[@]}"; do
    [[ -z "$l" ]] && continue
    l="${l#spdx:}"
    if [[ -n "$_license_str" ]]; then
        _license_str+=" AND ${l}"
    else
        _license_str="$l"
    fi
done
[[ -z "$_license_str" ]] && _license_str="Unknown"

# Generate the spec file
SPEC_FILE="${OUTDIR}/${SRCDIR}.spec"
msg "Generating ${SPEC_FILE}..."

cat > "${SPEC_FILE}" <<SPEC
# Auto-generated by make-mingw-srpm.sh from MINGW-packages/${SRCDIR}/PKGBUILD
%global pkgbase ${SRCDIR}

Name:           ${_pkgname[0]:-${PKG}}
Version:        ${_pkgver}
Release:        ${_pkgrel}%{?dist}
Summary:        ${_pkgdesc}
License:        ${_license_str}
URL:            ${_url}
ExclusiveArch:  x86_64

$(printf '%s\n' "${_spec_sources[@]}")

%global debug_package %{nil}

BuildRequires:  msys2-cross
BuildRequires:  msys2-cross-extra-deps
BuildRequires:  fakeroot
$([ "$_has_git_source" -eq 1 ] && echo "BuildRequires:  git")
${BUILD_DEPS}

Requires:       msys2-cross
${RUN_DEPS}

%description
${_pkgdesc}

Cross-compiled for Windows x86_64 (UCRT64) using msys2-cross.

%prep
%setup -q -c -T -n %{name}-%{version}
tar xf %{SOURCE0}
${_prep_copies}
%build
unset CFLAGS CXXFLAGS FFLAGS FCFLAGS LDFLAGS RUSTFLAGS CC CXX AR NM RANLIB
export PATH="/opt/msys2-cross/wrappers:/opt/msys2-cross/config:\${PATH}"
source /opt/msys2-cross/config/mingw-env.sh

cd %{pkgbase}
SPEC

# Cross-patch: reference the correct Source index (must be outside single-quoted heredoc)
if [[ "$HAS_CROSS_PATCH" -eq 1 ]]; then
    cat >> "${SPEC_FILE}" <<SPEC
# Apply msys2-cross cross-compilation patch
bash %{SOURCE${CROSS_PATCH_SRC_IDX}}
SPEC
fi

cat >> "${SPEC_FILE}" <<'SPEC'
makepkg-mingw --skipchecksums --nodeps --nocheck -f

%install
for pkg in %{_builddir}/%{name}-%{version}/%{pkgbase}/*.pkg.tar.*; do
    [ -f "$pkg" ] || continue
    bsdtar -xf "$pkg" -C %{buildroot}/ \
        --exclude=.PKGINFO --exclude=.BUILDINFO --exclude=.MTREE
done

_PACMAN_CONF=$(mktemp)
cat > "${_PACMAN_CONF}" <<PACCONF
[options]
RootDir     = %{buildroot}/
DBPath      = %{buildroot}/var/lib/pacman/mingw/
CacheDir    = %{buildroot}/var/cache/pacman/mingw/pkg/
LogFile     = /dev/null
Architecture = x86_64 auto
SigLevel = Never
PACCONF
mkdir -p %{buildroot}/var/lib/pacman/mingw
mkdir -p %{buildroot}/var/cache/pacman/mingw/pkg
fakeroot pacman --config "${_PACMAN_CONF}" -U --dbonly --noconfirm \
    --overwrite='*' \
    %{_builddir}/%{name}-%{version}/%{pkgbase}/*.pkg.tar.* || true
rm -f "${_PACMAN_CONF}"

%files
/ucrt64
/var/lib/pacman/mingw
SPEC

# Changelog needs variable expansion, so use unquoted heredoc
cat >> "${SPEC_FILE}" <<SPEC

%changelog
* $(date '+%a %b %d %Y') $(git config user.name) <$(git config user.email)> - ${_pkgver}-${_pkgrel}
- Auto-generated from MINGW-packages/${SRCDIR} PKGBUILD
SPEC

msg "Spec file written: ${SPEC_FILE}"

# Build SRPM
msg "Building SRPM..."
rpmbuild -bs "${SPEC_FILE}" \
    --define "_sourcedir ${OUTDIR}" \
    --define "_srcrpmdir ${OUTDIR}" \
    2>&1

SRPM=$(ls -t "${OUTDIR}"/*.src.rpm 2>/dev/null | head -1)
if [[ -n "$SRPM" ]]; then
    msg "SRPM: ${SRPM}"
else
    err "SRPM build failed"
    exit 1
fi
